services:
  - type: web
    name: slackbot
    env: node
    buildCommand: npm install
    startCommand: node bot.js
    envVars:
      - key: SLACK_BOT_TOKEN
        sync: false
      - key: SLACK_APP_TOKEN
        sync: false